---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "selfie2anime-slim-config"
  namespace: "default"
  labels:
    app: "selfie2anime-slim"
data:
  QUEUE_NAME: "selfie2anime"
  BUCKET_NAME: "selfie2anime"
  SENDER_EMAIL: "noreply@selfie2anime.com"
  AWS_ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxx"
  AWS_SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  AWS_DEFAULT_REGION: "us-east-1"
  PYTHONUNBUFFERED: "1"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "selfie2anime-slim"
  namespace: "default"
  labels:
    app: "selfie2anime-slim"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "selfie2anime-slim"
  template:
    metadata:
      labels:
        app: "selfie2anime-slim"
    spec:
      containers:
      - name: "selfie2anime"
        image: "gcr.io/devopstar/selfie2anime-ugatit:latest"
        imagePullPolicy: "Always"
        env:
        - name: "QUEUE_NAME"
          valueFrom:
            configMapKeyRef:
              key: "QUEUE_NAME"
              name: "selfie2anime-slim-config"
        - name: "BUCKET_NAME"
          valueFrom:
            configMapKeyRef:
              key: "BUCKET_NAME"
              name: "selfie2anime-slim-config"
        - name: "SENDER_EMAIL"
          valueFrom:
            configMapKeyRef:
              key: "SENDER_EMAIL"
              name: "selfie2anime-slim-config"
        - name: "AWS_ACCESS_KEY_ID"
          valueFrom:
            configMapKeyRef:
              key: "AWS_ACCESS_KEY_ID"
              name: "selfie2anime-slim-config"
        - name: "AWS_SECRET_ACCESS_KEY"
          valueFrom:
            configMapKeyRef:
              key: "AWS_SECRET_ACCESS_KEY"
              name: "selfie2anime-slim-config"
        - name: "AWS_DEFAULT_REGION"
          valueFrom:
            configMapKeyRef:
              key: "AWS_DEFAULT_REGION"
              name: "selfie2anime-slim-config"
        - name: "PYTHONUNBUFFERED"
          valueFrom:
            configMapKeyRef:
              key: "PYTHONUNBUFFERED"
              name: "selfie2anime-slim-config"
        resources:
          requests:
            memory: 4.5Gi
            cpu: 1000m
